### ISSUE TITLE
Details about data preprocessing

### ISSUE THREAD

**Issue by Mobbyjj** [NILOIDE/CMR_intensity_3Dmoco#1]
Hi, 

Thank you for posting the algorithms about the motion correction.

I noticed that there is "seg_sa_{i:02d}-{num_slices:02d}.nii.gz" corresponding to each"sa_{i:02d}-{num_slices:02d}.nii.gz". Could you specify what seg files contain? Say just the bounding box to tell whether the intersection points or detailed delineation of the myocardium? 

Also could you explain how it works within the code? I found they are stored in the data_classes.py L79 of self.planes but don't understand how they are used. 

Looking forward to your reply.

**Comment by NILOIDE** [comment]
The segmentation files are not used at all for the optimization. 
We have a private dataset of segmentations alongside our images. We used the post-optimization orientation to save new segmentations NIFTIs, so as to visualize the them on an external tool to visually validate our results. 

If I recall correctly, the code should still run without the segmentations. I can give it another look if you're facing an issue.
